# Site settings
title: zone
email: your-email@domain.com
description: my website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thedaniel.zone" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
